version: "3"
services:
  server:
    image: hw-tink-1:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    depends_on:
      - pg-server-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-server-db/server_db

  pg-server-db:
    image: postgres:14-alpine3.18
    container_name: server_db
    environment:
      POSTGRES_DB: "server_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - server-db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  server-db:
