spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:15432/server_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/server
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 30000
  redis:
    host: localhost
    port: 6379
    password: RedisPassword
  liquibase:
    change-log: classpath:liquibase/master.xml

minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760

server:
  port: 8080

logging:
  level:
    liquibase: info
